### ISSUE TITLE
formshandlers.mercer.edu

### ISSUE THREAD

**Issue by elcopeland** [merceruniversity/team-planning#12]
Style new email template

Repo: https://github.com/InteractiveDesignAndDevelopment/formhandlers

**Comment by elcopeland** [comment]
![image](https://user-images.githubusercontent.com/22402707/32899356-c44809b4-cab8-11e7-9092-aae006730699.png)

**Comment by Sporkyy** [comment]
The migration isn't complete, but the new formhandlers.mercer.eud site has launched. Maybe this can be closed. Depending on the intention behind it. @elcopeland
