### ISSUE TITLE
Student Affairs

### ISSUE THREAD

**Issue by elcopeland** [merceruniversity/team-planning#16]

**Comment by elcopeland** [comment]
Michele was sick this week, so didn't get to complete it Wednesday. Perhaps monday.

**Comment by cinakur** [comment]
- [x] ACCESS and Accommodations
- [x] Campus Life
- [x] Counseling and Psychological Services
- [x] Center for Career and Professional Development
- [x] Judicial
- [x] Leadership
- [x] Minority Affairs
- [x] Recreational Sports and Wellness
- [x] Residence Life
- [x] Student Government Association
- [x] Student Health
- [x] TRIO Programs

**Comment by cinakur** [comment]
## To Do before launch
- [x] Student Health Content 
- [x] Resources Link on link bar (El) 
- [x] Delete /studentaffairs/contact
- [x] Resize and upload images for index
- [x] Departments (Hannah)

**Comment by cinakur** [comment]
## Brittany 
- [x] Disability Statement link in the Miscellaneous Info section on this Tift page: http://education.mercer.edu/faculty/faculty-resources/
- [x] Student Health and Counseling link in the Student Health section on this Tift page: http://education.mercer.edu/about/campuses-centers/savannah/
- [x] Student Health and Counseling link in the Student Health section of this Tift page: http://education.mercer.edu/about/campuses-centers/atlanta/
- [x] Student Health and Counseling link in the Student Health section of this Penfield page: http://penfield.mercer.edu/about-penfield/campuses/atlanta/
- [x] Student Health and Counseling link in the Student Health section of this Penfield page: http://penfield.mercer.edu/about-penfield/campuses/douglas/
## For Hannah

- [ ] https://campuslife.mercer.edu/atlanta/student-orgs/policy/ 
- [ ] The “Download registration form” link does not link to the appropriate form. (Organization Registration)
- [ ] Farther down on this page, under Campus & Residence Life posting policy info, the link to the list of approved posting locations should be updated to the new map. (Posting map Feb 2018) 
- [ ] https://campuslife.mercer.edu/atlanta/programs/
- [ ] Under the Marketing Guidelines: Atlanta Campus Wide Email and DMP heading, Hannah Lawrence is listed as the contact. Her email is displayed correctly, but when clicked on, it does not lead to her email address. The rest on this page are correct! 

## For Elizabeth
- [x] https://access.mercer.edu/campuses/atlanta-centers/
- [x] I am unable to click on stilley_r@mercer.edu to send an email. (Very possible user error but pointing it out just in case!)
- [x] The link that follows “For more information about the campus please see the website” links to https://campuslife.mercer.edu/atlanta/ which is correct, but the displayed website is no longer accurate.
- [x] https://access.mercer.edu/contact/
- [x] I am unable to click Katie Johnson’s email. Richard Stilley’s works though! 
- [x] https://minorityaffairs.mercer.edu/
- [x] The “tutoring and mentoring” link should lead to https://minorityaffairs.mercer.edu/mentor-program/tutoring/
- [x] https://rsw.mercer.edu/atlanta/aquatics/
- [x] At the bottom, where it says visit the monthly pool calendar at: the link should be https://sheffield.mercer.edu/www/mu-sheffield/upload/Field-Sched-MAR-2018.pdf which is a PDF, or to https://sheffield.mercer.edu/aquatics/#aerobicsClasses where they can find the link to the PDF.

**Comment by cinakur** [comment]
## For Katie
- [x] CMS.mercer.edu
- [x] Logging in to your site
- [x] Navigation
- [x] Finding already uploaded Files
- [ ] Specific Issues
- [ ] Under the MercerSAVE tab:
- [ ] The first two “click here” links (Bystander Intervention and Prevention & Risk Reduction Strategies) are broken links. They will decide if they want them removed or updated, but that is TBD.
- [ ] Statements, Definitions, and Compliance Support Brochure is attached.
- [x] Engaged Bears Brochure – Atlanta is attached.
- [ ] Atlanta Campus Brochure should link to the Atlanta CAPS Brochure attached.
- [x] The remaining campus brochures are TBD.
- [ ] https://counseling.mercer.edu/emergency-situations/
- [ ] Under the For Mercer Faculty and Staff tab, ” There are a number of warning signs to look for and we have detailed those signs here” should link to the Helping Distressed Students Brochure.
