### ISSUE TITLE
easy listservs

### ISSUE THREAD

**Issue by elcopeland** [merceruniversity/team-planning#24]
https://github.com/InteractiveDesignAndDevelopment/easy-listservs

**Comment by elcopeland** [comment]
Spent afternoon looking at [Look at Class Listservs](https://github.com/InteractiveDesignAndDevelopment/easy-listservs/blob/master/lookup-class-listservs.html). It appears that URI.js is encoding spaces properly for a query, however, we need it to encode spaces for a URL.

**Comment by elcopeland** [comment]
To research this week: 

Can we get URI.js to encode "+" as "%20" instead of "+"? 

(We want it to break spec, essentially)

**Comment by Sporkyy** [comment]
I just gave up and did it without URI.js. It makes things easier, but it's too much to be worth it here.

**Comment by Sporkyy** [comment]
With the technical issues behind us (ha ha), the next concern is the interface on these pages.

http://it.mercer.edu/faculty/email/email_listservs-special_interest_listservs.htm
http://it.mercer.edu/student/email/email_listservs-special_interest_listservs.htm

The email address field goes away and I think every listserv listed gets its own subscribe and unsubscribe button.

**Comment by cinakur** [comment]
Would it be infeasible/too much to have Subscribe/Unsubscribe/No Answer radio buttons (errrr....dropdown selector?) for each listserv

**Comment by Sporkyy** [comment]
Yes? The old form worked behind the scenes sending multiple emails. The new page won't have a form and will just use mailto links. I think opening multiple emails simultaneously would be too much. So just...

- one listserve
- one operation (sub/unsubscribe)
- one button  

...at a time makes the most sense.

The whole system is dependent on who the email is from. There are other ways of doing it (running email lists), but that's how it's done here.

**Comment by cinakur** [comment]
you saying like [this](https://www.figma.com/file/hBRyyd8ygg7aAuknK8lUWkHo/Untitled?node-id=6%3A1), @Sporkyy ?

**Comment by Sporkyy** [comment]
Yes, prezactly. But I was going to break out of the table too.

**Comment by Sporkyy** [comment]
And, also, like the other form, there won't be an email address field.

It's opening your default email client and creating a well-formed email subject+body for you.

**Comment by cinakur** [comment]
ah yep durrr

**Comment by cinakur** [comment]
The last thing I'm thinking through here is that text should explain what users need to do when their email client opens. Or atleast that is the correct behavior

**Comment by cinakur** [comment]
Launched; needs some front end stuff and also some submission stuff (not honeypot), but nothing critical.
